#!/bin/bash

clear
echo "Monitoring src/ for changes..."

mkdir -p bin

inotifywait -q -m -r -e modify src | while read -r _DIRECTORY EVENT FILE; do
  # echo $DIRECTORY $EVENT $FILE
  case $EVENT in
    MODIFY*)
      if [ "${FILE##*.}" = "ml" ]; then
        clear
        EXE=${FILE%%.*}
        echo "= ${FILE} ==============================="; echo
        ocamlopt -o bin/${EXE} src/${FILE}
        ./bin/${EXE}
        echo; echo "= $(date) ==================="
      fi
      ;;
  esac
done
